spring.application.name: recommendation-service
server.port: 8001
security.basic.enabled: false
eureka:
  client.serviceUrl.defaultZone: ${eureka.url:http://localhost:8761}/eureka
  instance.preferIpAddress: true

jwt.secret.key: m0vi3s@pp